source 'https://github.com/CocoaPods/Specs.git'

target 'IDDaDataSuggestions', :exclusive => true do
  pod "IDDaDataSuggestions", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "IDDaDataSuggestions", :path => "../"

  
end
